### ISSUE TITLE
Help reviewing remaining PRs for 0.9.1

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#725]
We had a lot of changes since 0.9.0 came out, and all issues we have on 0.9.1 milestone have a Pull Request open. I would like to merge these soon so we can release 0.9.1 and start focusing on 0.9.2. 

These are the PRs I have in mind so far:

- [x] [need review] [semantic,codegen: allow optional positional params](https://github.com/iovisor/bpftrace/pull/742)
- [x] [changes requested] [Fully implement ++ and -- #486](https://github.com/iovisor/bpftrace/pull/486)
- [x] [need review] [codegen: fix ntop usage with maps and printf #762](https://github.com/iovisor/bpftrace/pull/762)
- [x] [need review] [clang_parser: workaround for asm goto in Kernel 5+ headers #732](https://github.com/iovisor/bpftrace/pull/732)
- [x] [need review] [[tests] add missing tests to codegen.cpp #574](https://github.com/iovisor/bpftrace/pull/574)
- [x] [need review] [Fix attaching to USDT probes with semaphore and USDT runtime tests #691](https://github.com/iovisor/bpftrace/pull/691)
- [x] [need review] [Parse negative integer literals correctly #623](https://github.com/iovisor/bpftrace/pull/623)
- [x] [need review] [bison: introduce compound assignment operators #448](https://github.com/iovisor/bpftrace/pull/448)
- [x] [need review] [Fix error handling of invalid 'args' utilization #726](https://github.com/iovisor/bpftrace/pull/726)
- [x] [need review] [semantic_analyzer: check if positional parameters was given #723](https://github.com/iovisor/bpftrace/pull/723)
- [x] [need review] [codegen: don't rely on LLVM unrolling our loops #722](https://github.com/iovisor/bpftrace/pull/722)
- [x] [need review] [tests: fix and improve runtime tests #690](https://github.com/iovisor/bpftrace/pull/690)

If folks could help reviewing those PRs, that would be awesome.

Also, if there are other PRs folks believe should go in our next release, please comment here so we can decide if it should be included or not. I would like to avoid merging big or impactful changes before we release 0.9.1 (especially https://github.com/iovisor/bpftrace/pull/535, https://github.com/iovisor/bpftrace/pull/667 and https://github.com/iovisor/bpftrace/pull/711) since it would be nice to have those changes in `master` for a few weeks before they make into a release.

**Comment by danobi** [comment]
I volunteer #623 to be included :)

**Comment by danobi** [comment]
I can help review some stuff.

**Comment by mmarchini** [comment]
> I volunteer #623 to be included :)

Makes sense, and doesn't look like something risky to have in the next release. I'll add to the list :)

**Comment by mmarchini** [comment]
Should we include https://github.com/iovisor/bpftrace/pull/714? On one hand it fixes two issues, on the other hand I'm worried of having it in a release without having it on master for some time first.

**Comment by danobi** [comment]
I think it should bake in master a bit. I don't think it's a critical bug.

**Comment by mmarchini** [comment]
I'll add #732 since several users are facing this issue.

**Comment by mmarchini** [comment]
Also adding https://github.com/iovisor/bpftrace/pull/762 because it fixes a critical issue with ntop.

**Comment by danobi** [comment]
Should we cut release branches instead of doing version-freeze tags on PRs?

**Comment by mmarchini** [comment]
Yes, that would be better.

**Comment by mmarchini** [comment]
I'm writing the changelog for 0.9.1 now. I think maybe https://github.com/iovisor/bpftrace/pull/742 should be included as well, otherwise we'll introduce a breaking change in this version (disallow optional positional parameters) just to reverto to the old behavior in the next version.

**Comment by ajor** [comment]
All PRs merged!

**Comment by mmarchini** [comment]
v0.9.1 was released today, so I'll close this issue.

Thank you for everyone who helped with reviews and pull requests!
